### ISSUE TITLE
Resource pack loading breaks player login with BungeeCord 1.12.1.

### ISSUE THREAD

**Issue by mibby** [Phoenix616/ResourcepacksPlugins#11]
Waterfall dev 133 (BungeeCord 1.12.1) https://ci.destroystokyo.com/view/All/job/Waterfall/
Paper dev 1170 (Spigot 1.12.1) https://ci.destroystokyo.com/job/PaperSpigot/
BungeeResourcePack dev 198 https://ci.minebench.de/job/ResourcepacksPlugins/

@Phoenix616 Resource pack loading breaks player login with BungeeCord 1.12.1. Players who attempt to connect to the server on minecraft 1.12.1 get disconnected with an IndexOutOfBoundsException readerIndex / length exceeding exception. Removing the plugin, players are able to login fine again.

Some BungeeCord log errors, but not sure it is related to the connecting since it doesn't output for everyone. However login does break for everyone.
```
io.netty.handler.codec.DecoderException: Error decoding packet class ResourcePackSendPacket with contents:
         +-------------------------------------------------+
         |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |
+--------+-------------------------------------------------+----------------+
|00000000| 33 8b 08 03                                     |3...            |
+--------+-------------------------------------------------+----------------+
	at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:68)
	at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:12)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:979)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:403)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:306)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IndexOutOfBoundsException: readerIndex(3) + length(1035) exceeds writerIndex(4): UnpooledSlicedByteBuf(ridx: 3, widx: 4, cap: 4/4, unwrapped: PooledUnsafeDirectByteBuf(ridx: 5, widx: 5, cap: 128))
	at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1396)
	at io.netty.buffer.AbstractByteBuf.checkReadableBytes(AbstractByteBuf.java:1383)
	at io.netty.buffer.AbstractByteBuf.readBytes(AbstractByteBuf.java:850)
	at io.netty.buffer.AbstractByteBuf.readBytes(AbstractByteBuf.java:858)
	at net.md_5.bungee.protocol.DefinedPacket.readString(DefinedPacket.java:36)
	at de.themoep.resourcepacksplugin.bungee.packets.ResourcePackSendPacket.read(ResourcePackSendPacket.java:86)
	at net.md_5.bungee.protocol.DefinedPacket.read(DefinedPacket.java:193)
	at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:46)
	... 23 more
```
```
io.netty.handler.codec.DecoderException: Error decoding packet class ResourcePackSendPacket with contents:
         +-------------------------------------------------+
         |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |
+--------+-------------------------------------------------+----------------+
|00000000| 33 8e 10 01                                     |3...            |
+--------+-------------------------------------------------+----------------+
	at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:68)
	at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:12)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:297)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:413)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:979)
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:403)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:306)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IndexOutOfBoundsException: readerIndex(3) + length(2062) exceeds writerIndex(4): UnpooledSlicedByteBuf(ridx: 3, widx: 4, cap: 4/4, unwrapped: PooledUnsafeDirectByteBuf(ridx: 5, widx: 14, cap: 512))
	at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1396)
	at io.netty.buffer.AbstractByteBuf.checkReadableBytes(AbstractByteBuf.java:1383)
	at io.netty.buffer.AbstractByteBuf.readBytes(AbstractByteBuf.java:850)
	at io.netty.buffer.AbstractByteBuf.readBytes(AbstractByteBuf.java:858)
	at net.md_5.bungee.protocol.DefinedPacket.readString(DefinedPacket.java:36)
	at de.themoep.resourcepacksplugin.bungee.packets.ResourcePackSendPacket.read(ResourcePackSendPacket.java:86)
	at net.md_5.bungee.protocol.DefinedPacket.read(DefinedPacket.java:193)
	at net.md_5.bungee.protocol.MinecraftDecoder.decode(MinecraftDecoder.java:46)
	... 25 more
```

**Comment by mibby** [comment]
I tried manually compiling the source in case it needed to be compiled against BungeeCord again. Unfortunately didn't resolve the problem.

![link](http://i.imgur.com/MA8mS8G.png)

Removing the plugin, players are able to connect again.

**Comment by Phoenix616** [comment]
The plugin is not yet updated to 1.12.1 so it makes sense that there are errors as 1.12.1 introduced a new Protocol version and changed the packet IDs used to send resource packs.
