### ISSUE TITLE
IllegalAccessError: failed to access class net.md_5.bungee.protocol.Protocol$DirectionData

### ISSUE THREAD

**Issue by mibby** [Phoenix616/ResourcepacksPlugins#23]
Waterfall dev 258 (BungeeCord 1.13.2)
BungeeResourcePack dev 259

Broke from a newer BungeeCord commit? https://github.com/SpigotMC/BungeeCord/commit/9133a6f511b4cfaca5e6a6671b58a6c3b10821ab#diff-f5da6738ad3c03e59c357db9fd022745R282
```
[08:52:00] [main/INFO] [BungeeResourcepacks]: BungeeCord 1.9.4+ (404) detected!
[08:52:00] [main/INFO] [BungeeResourcepacks]: Registered ResourcePackSendPacket for 1.8
[08:52:00] [main/INFO] [BungeeResourcepacks]: Registered ResourcePackSendPacket for 1.9
[08:52:00] [main/INFO] [BungeeResourcepacks]: Registered ResourcePackSendPacket for 1.12
[08:52:00] [main/INFO] [BungeeResourcepacks]: Registered ResourcePackSendPacket for 1.12.1
[08:52:00] [main/INFO] [BungeeResourcepacks]: Registered ResourcePackSendPacket for 1.12.2
[08:52:00] [main/INFO] [BungeeResourcepacks]: Registered ResourcePackSendPacket for 1.13
[08:52:00] [main/INFO] [BungeeResourcepacks]: Registered ResourcePackSendPacket for 1.13.1
[08:52:00] [main/INFO] [BungeeResourcepacks]: Registered ResourcePackSendPacket for 1.13.2
[08:52:00] [main/WARN]: Exception encountered when loading plugin: BungeeResourcepacks
java.lang.IllegalAccessError: failed to access class net.md_5.bungee.protocol.Protocol$DirectionData from class de.themoep.resourcepacksplugin.bungee.BungeeResourcepacks (net.md_5.bungee.protocol.Protocol$DirectionData is in unnamed module of loader 'app'; de.themoep.resourcepacksplugin.bungee.BungeeResourcepacks is in unnamed module of loader net.md_5.bungee.api.plugin.PluginClassloader @5b22b970)
	at de.themoep.resourcepacksplugin.bungee.BungeeResourcepacks.onEnable(BungeeResourcepacks.java:160) ~[?:?]
	at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:282) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:1732f85:258]
	at net.md_5.bungee.BungeeCord.start(BungeeCord.java:282) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:1732f85:258]
	at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:56) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:1732f85:258]
	at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15) ~[BungeeCord.jar:git:Waterfall-Bootstrap:1.13-SNAPSHOT:1732f85:258]

```

**Comment by mibby** [comment]
Confirmed caused by BungeeCord commit https://github.com/SpigotMC/BungeeCord/commit/9133a6f511b4cfaca5e6a6671b58a6c3b10821ab

Downgrading to Waterfall dev 256, all is fine again.

**Comment by DRSchlaubi** [comment]
Any workaround besides switching back to older bungeecord?

**Comment by Phoenix616** [comment]
This has been fixed since February, make sure you are running the latest build.

**Comment by DRSchlaubi** [comment]
I encounter the same error on Waterfall #300
```
[13:51:42 WARN]: Exception encountered when loading plugin: BungeeResourcepacks
java.lang.IllegalAccessError: tried to access class net.md_5.bungee.protocol.Protocol$DirectionData from class de.themoep.resourcepacksplugin.bungee.BungeeResourcepacks
at de.themoep.resourcepacksplugin.bungee.BungeeResourcepacks.onEnable(BungeeResourcepacks.java:121) ~[?:?]
at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:283) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:b704f4c:300]
at net.md_5.bungee.BungeeCord.start(BungeeCord.java:281) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:b704f4c:300]
at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:62) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:b704f4c:300]
at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15) ~[bungeecord.jar:git:Waterfall-Bootstrap:1.14-SNAPSHOT:b704f4c:300]``` also tried using latest travertine and bungeecord build

**Comment by Phoenix616** [comment]
Which plugin version are you running?

**Comment by DRSchlaubi** [comment]
1.6.14

**Comment by Phoenix616** [comment]
That's a really old version, please update to one of the latest development builds.

**Comment by DRSchlaubi** [comment]
It was the latest build on GitHub upgraded to newest dev buid and it works
