### ISSUE TITLE
Error when players try join with unsupported version

### ISSUE THREAD

**Issue by andris155** [Phoenix616/ResourcepacksPlugins#45]
#### Used Version

1.8.3-SNAPSHOT (build 355)
 
 
#### Config

 ```yaml
debug: false
default-language: en
disable-metrics: false
autogeneratehashes: true
usepack-is-temporary: true
stored-packs-override-assignments: false
permanent-pack-remove-time: 30
packs:
  acidisland:
    url: https://github.com/andris155/TheOld-Crafters/blob/master/Savsziget_v2_1.16.2.zip?raw=true
    hash: 2f236ed8c68aae6882162a148d47267fd283b4ea
  oldspace:
    url: https://github.com/andris155/TheOld-Crafters/blob/master/OldSpace.zip?raw=true
    hash: b597c94557f8f6237c72940e1cb54e3c454cd483
empty:
  url: https://github.com/andris155/TheOld-Crafters/blob/master/SVR.zip?raw=true
  hash: 8932b583aea660973752712cdf158dd8d6b486c2
global:
  send-delay: 20
servers:
  savsziget:
    pack: acidisland
  oldspace:
    pack: oldspace
 ```
 
#### Environment description

OS: Ubuntu 20.04
OS language: English 
Server version: Waterfall build 380
 
#### Full Log

```
[00:20:57] [Netty Worker IO Thread #16/INFO]: [MCI|/IP:36324] <-> ServerConnector [login] has connected
[00:20:57] [Netty Worker IO Thread #16/INFO]: [MCI] disconnected with: Ki lettél dobva, miközben csatlakozol a(z) login szerverhez: Outdated client! Supported version: 1.16.3
[00:20:57] [Netty Worker IO Thread #16/WARN] [global]: Error dispatching event PlayerDisconnectEvent(player=MCI) to listener de.themoep.resourcepacksplugin.bungee.listeners.DisconnectListener@9aa2002
java.lang.NullPointerException: null
	at de.themoep.resourcepacksplugin.bungee.BungeeResourcepacks.sendPackInfo(BungeeResourcepacks.java:665) ~[?:?]
	at de.themoep.resourcepacksplugin.bungee.BungeeResourcepacks.clearPack(BungeeResourcepacks.java:702) ~[?:?]
	at de.themoep.resourcepacksplugin.core.UserManager.onDisconnect(UserManager.java:97) ~[?:?]
	at de.themoep.resourcepacksplugin.bungee.listeners.DisconnectListener.onPlayerDisconnect(DisconnectListener.java:40) ~[?:?]
	at jdk.internal.reflect.GeneratedMethodAccessor29.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19) ~[waterfall-sqlite-B.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:d5978da:380]
	at net.md_5.bungee.event.EventBus.post(EventBus.java:47) ~[waterfall-sqlite-B.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:d5978da:380]
	at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:453) ~[waterfall-sqlite-B.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:d5978da:380]
	at net.md_5.bungee.connection.UpstreamBridge.disconnected(UpstreamBridge.java:66) ~[waterfall-sqlite-B.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:d5978da:380]
	at net.md_5.bungee.netty.HandlerBoss.channelInactive(HandlerBoss.java:60) ~[waterfall-sqlite-B.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:d5978da:380]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262) ~[waterfall-sqlite-B.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:d5978da:380]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248) ~[waterfall-sqlite-B.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:d5978da:380]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241) ~[waterfall-sqlite-B.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:d5978da:380]
	at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:389) ~[waterfall-sqlite-B.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:d5978da:380]
	at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:354) ~[waterfall-sqlite-B.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:d5978da:380]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262) ~[waterfall-sqlite-B.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:d5978da:380]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248) ~[waterfall-sqlite-B.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:d5978da:380]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241) ~[waterfall-sqlite-B.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:d5978da:380]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:81) ~[waterfall-sqlite-B.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:d5978da:380]
	at io.netty.handler.timeout.IdleStateHandler.channelInactive(IdleStateHandler.java:277) ~[waterfall-sqlite-B.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:d5978da:380]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262) ~[waterfall-sqlite-B.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:d5978da:380]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248) ~[waterfall-sqlite-B.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:d5978da:380]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241) ~[waterfall-sqlite-B.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:d5978da:380]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1405) ~[waterfall-sqlite-B.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:d5978da:380]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262) ~[waterfall-sqlite-B.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:d5978da:380]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248) ~[waterfall-sqlite-B.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:d5978da:380]
	at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:901) ~[waterfall-sqlite-B.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:d5978da:380]
	at io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:819) ~[waterfall-sqlite-B.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:d5978da:380]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) ~[waterfall-sqlite-B.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:d5978da:380]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) ~[waterfall-sqlite-B.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:d5978da:380]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:384) ~[waterfall-sqlite-B.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:d5978da:380]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[waterfall-sqlite-B.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:d5978da:380]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[waterfall-sqlite-B.jar:git:Waterfall-Bootstrap:1.16-R0.4-SNAPSHOT:d5978da:380]
	at java.lang.Thread.run(Unknown Source) [?:?]
```

#### What other programs/plugins are you running?

<img width="135" alt="Capture" src="https://user-images.githubusercontent.com/8324198/97764689-be886000-1b0f-11eb-8922-056ded49bf57.PNG">

#### What is happening?

Plugin writes error when players try join with unsupported version

#### What did you expect to happen?

No write this error.

**Comment by Phoenix616** [comment]
Can you please test with the latest dev build and ideall with Java 14/15 with the `-XX:+ShowCodeDetailsInExceptionMessages` startup parameter? Because that error should not really be possible...

**Comment by andris155** [comment]
Latest dev version fixed this issue.
Thanks!
The Minecraft servers usually uses LTS (8, and 11) java versions, not dev Java versions.
