### ISSUE TITLE
GeyserMC

### ISSUE THREAD

**Issue by gjorgdy** [Phoenix616/ResourcepacksPlugins#58]
I'm using VelocityResourcepacks together with GeyserMC on my Velocity server and it gives me this error:
```
[02:20:52 ERROR]: Exception in task de.themoep.resourcepacksplugin.velocity.listeners.ServerSwitchListener$$Lambda$1043/0x00000008010f5390@38a47353 by plugin VelocityResourcepacks
java.lang.NullPointerException: Cannot invoke "org.geysermc.connector.GeyserConnector.getPlayerByUuid(java.util.UUID)" because "this.geyserConnector" is null
at de.themoep.resourcepacksplugin.velocity.integrations.GeyserIntegration.hasPlayer(GeyserIntegration.java:37) ~[?:?]
at de.themoep.resourcepacksplugin.velocity.VelocityResourcepacks.getPlayerClientType(VelocityResourcepacks.java:705) ~[?:?]
at de.themoep.resourcepacksplugin.core.PackManager.checkPack(PackManager.java:927) ~[?:?]
at de.themoep.resourcepacksplugin.core.PackManager.getApplicablePack(PackManager.java:879) ~[?:?]
at de.themoep.resourcepacksplugin.core.PackManager.applyPack(PackManager.java:814) ~[?:?]
at de.themoep.resourcepacksplugin.velocity.listeners.ServerSwitchListener.calculatePack(ServerSwitchListener.java:79) ~[?:?]
at de.themoep.resourcepacksplugin.velocity.listeners.ServerSwitchListener.lambda$onServerSwitch$0(ServerSwitchListener.java:63) ~[?:?]
at com.velocitypowered.proxy.scheduler.VelocityScheduler$VelocityTask.lambda$run$1(VelocityScheduler.java:203) ~[BungeeCord.jar:3.0.1-SNAPSHOT (git-a037aebf-b38)]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
at java.lang.Thread.run(Thread.java:831) [?:?]
```

**Comment by Phoenix616** [comment]
Please provide your log file as requested in the issue template.

**Comment by gjorgdy** [comment]
[latest.log](https://github.com/Phoenix616/ResourcepacksPlugins/files/6945406/latest.log)

**Comment by Phoenix616** [comment]
This looks like a Velocity bug. For some reason it is enabling Geyser after VelocityResourcepacks even though this plugin depends on geyser hence it not being able to properly hook into it it seems.
