### ISSUE TITLE
Resource packs not loading

### ISSUE THREAD

**Issue by Redboy1012** [Phoenix616/ResourcepacksPlugins#59]
1.8.5 Used Version

 
 
#### Config

 ```yaml
# 
# Default language
debug: true
default-language: en
disable-metrics: false
autogeneratehashes: true
usepack-is-temporary: true
stored-packs-override-assignments: false
permanent-pack-remove-time: 30
empty:
  url: http://cdn.moep.tv/files/Empty.zip
  hash: 01517226212d27586ea0c5d6aff1aa5492dd2484
global:
  send-delay: 10
  secondary:
  - animation
  pack: tweaks
worlds:
  lobby:
    pack: lobbypack
  minigame:
    pack: gamepack
    regex: minigame_.*
packs:
  lobbypack:
    url: http://example.com/lobbyresourcepack.zip
    hash: abcdef012345678abcdef012345678abcdef0123
    format: 1
    version: '1.8'
    restricted: false
    permission: worldresourcepacks.pack.lobbypack
  gamepack:
    restricted: false
    permission: worldresourcepacks.pack.gamepack
    variants:
    - url: http://example.com/minigameresourcepack_1_15.zip
      hash: 012345678abcdef012345678abcdef012345678a
      format: null
      version: '1.15'
      restricted: false
      permission: worldresourcepacks.pack.gamepack-variant-1
      type: null
      variants: null
    - url: http://example.com/minigameresourcepack_1_12.zip
      hash: 012345678abcdef01234567dddcdef012345678a
      format: null
      version: '1.12'
      restricted: false
      permission: worldresourcepacks.pack.gamepack-variant-2
      type: null
      variants: null
  tweaks:
    url: https://download.mc-packs.net/pack/4e24a410c924ac94ec2b71dca77c590c3e35d2e3.zip
    hash: 4e24a410c924ac94ec2b71dca77c590c3e35d2e3
    restricted: false
    permission: resourcepacksplugin.pack.tweaks
  animation:
    url: https://download.mc-packs.net/pack/6425cb0bb71baf3540f64d13eebf9da1730e80ff.zip
    hash: 6425cb0bb71baf3540f64d13eebf9da1730e80ff
    restricted: false
    permission: resourcepacksplugin.pack.animation

 ```
 
#### Full Log

```
[13:34:05] [main/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[13:34:05] [main/WARN]: Couldn't get pack info for: net.minecraft.server.packs.ResourceNotFoundException: 'pack.mcmeta' in ResourcePack '.\world\datapacks\VanillaTweaks_d941067_UNZIP_ME.zip'
[13:34:05] [main/INFO]: Reloading ResourceManager: Default, terralith-v1-3a.zip, new-in-town-by-kanokarob-v2-7-2.zip, bukkit, VanillaTweaks_c234012.zip
[13:34:06] [Worker-Main-5/INFO]: Loaded 7 recipes
[13:34:07] [Server thread/INFO]: Starting minecraft server version 1.17.1
[13:34:07] [Server thread/INFO]: Loading properties
[13:34:07] [Server thread/INFO]: This server is running Paper version git-Paper-169 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT) (Git: 25cd8ab)
[13:34:07] [Server thread/INFO]: Debug logging is disabled
[13:34:07] [Server thread/INFO]: Server Ping Player Sample Count: 12
[13:34:07] [Server thread/INFO]: Using 4 threads for Netty based IO
[13:34:07] [Server thread/WARN]: You specified a resource pack without providing a sha1 hash. Pack will be updated on the client only if you change the name of the pack.
[13:34:07] [Server thread/INFO]: Default game type: SURVIVAL
[13:34:07] [Server thread/INFO]: Generating keypair
[13:34:07] [Server thread/INFO]: Starting Minecraft server on *:25565
[13:34:07] [Server thread/INFO]: Using default channel type
[13:34:08] [Server thread/INFO]: [EnchantableBlocks] Loading 1 libraries... please wait
[13:34:08] [Server thread/INFO]: [EnchantableBlocks] Loaded library C:\Users\redbo\Desktop\Minecraft Servers\Paper 1.17\libraries\it\unimi\dsi\fastutil\8.5.4\fastutil-8.5.4.jar
[13:34:08] [Server thread/INFO]: [EnchantableBlocks] Loaded library C:\Users\redbo\Desktop\Minecraft Servers\Paper 1.17\libraries\it\unimi\dsi\fastutil-extra\8.5.4\fastutil-extra-8.5.4.jar
[13:34:08] [Server thread/INFO]: [EnchantableBlocks] Loaded library C:\Users\redbo\Desktop\Minecraft Servers\Paper 1.17\libraries\it\unimi\dsi\fastutil-core\8.5.4\fastutil-core-8.5.4.jar
[13:34:08] [Server thread/INFO]: [PlayerHeads] Loading PlayerHeads v5.2.12-SNAPSHOT
[13:34:08] [Server thread/INFO]: [PlayerHeads] Internal plugin locale: 
[13:34:08] [Server thread/INFO]: [PlayerHeads] Environment locale: en_US / en-US
[13:34:08] [Server thread/INFO]: [PlayerHeads] [STDOUT] Trying provider: craftbukkit_1_16
[13:34:08] [Server thread/WARN]: Nag author(s): '[meiskam, zand, crashdemons]' of 'PlayerHeads' about their usage of System.out/err.print. Please use your plugin's logger instead (JavaPlugin#getLogger).
[13:34:08] [Server thread/INFO]: [dynmap] Loading dynmap v3.2-beta-2-483
[13:34:08] [Server thread/INFO]: [dynmap] version=git-Paper-169 (MC: 1.17.1)
[13:34:08] [Server thread/INFO]: [dynmap] Mod Support API available
[13:34:08] [Server thread/INFO]: [Enchantments_plus] Loading Enchantments_plus v4.0.1
[13:34:08] [Server thread/INFO]: [SMPtweaks] Loading SMPtweaks v1.0.9-beta
[13:34:08] [Server thread/INFO]: [Magic] Loading Magic v9.4.4-e8def57
[13:34:09] [Server thread/INFO]: [Magic] Loading modern compatibility layer for server version 1.17.1
[13:34:09] [Server thread/INFO]: [Magic] Async chunk loading API found
[13:34:09] [Server thread/INFO]: [ServerMinimap] Loading ServerMinimap v0.7.24
[13:34:09] [Server thread/INFO]: [WorldResourcepacks] Loading WorldResourcepacks v1.8.5 (build 417)
[13:34:09] [Server thread/INFO]: [DiscordSRV] Loading DiscordSRV v1.23.0
[13:34:09] [Server thread/INFO]: [Nova] Loading Nova v0.4
[13:34:09] [Server thread/INFO]: [EnchantableBlocks] Loading EnchantableBlocks v3.0.0
[13:34:09] [Server thread/INFO]: [VehicleStorage] Loading VehicleStorage v1.1.0
[13:34:09] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[13:34:09] [Server thread/INFO]: [Magic] Enabling Magic v9.4.4-e8def57
[13:34:09] [Server thread/INFO]: [Magic] EffectLib initialized
[13:34:10] [Server thread/ERROR]: [[STDERR] ] org.bukkit.craftbukkit.v1_17_R1.legacy.CraftLegacy Initializing Legacy Material Support. Unless you have legacy plugins and/or data this is a bug!
[13:34:12] [Server thread/INFO]: [Magic] Loaded 0 attributes
[13:34:13] [Server thread/INFO]: [Magic] Wand crafting is enabled
[13:34:13] [Server thread/INFO]: [Magic] Skin-based spell icons disabled
[13:34:13] [Server thread/INFO]: [Magic] Registered attributes: [target_fall_distance, luck, target_hunger, location_x, location_y, target_mana, attack_damage, bowpower, degrees, knockback_resistance, seconds, location_z, humidity, target_air, health_max, target_luck, level, minutes, target_armor, fall_distance, hunger, target_health_max, moon, armor, air_max, mana_max, bowpull, damage, damage_dealt, weeks, epoch, air, temperature, target_mana_max, hours, health, target_temperature, target_air_max, movement_speed, play_time, mana, target_health, xp, target_location_x, target_humidity, days, pi, target_location_y, target_knockback_resistance, target_location_z, time]
[13:34:13] [Server thread/INFO]: [Magic] Loaded 0 customized worlds
[13:34:13] [Server thread/INFO]: [Magic] Loaded 12 effect lists
[13:34:13] [Server thread/INFO]: [Magic] Loaded 1401 items
[13:34:13] [Server thread/INFO]: [Magic] Loaded 175 wands
[13:34:13] [Server thread/INFO]: [Magic] Loaded 2 kits
[13:34:13] [Server thread/INFO]: [Magic] Loaded 10 classes
[13:34:13] [Server thread/INFO]: [Magic] Loaded 3 classes
[13:34:13] [Server thread/INFO]: [Magic] Loaded 66 mob templates
[13:34:13] [Server thread/INFO]: [Magic] Loaded 7 automata templates
[13:34:13] [Server thread/INFO]: [Magic] Activated BStats
[13:34:13] [Server thread/INFO]: [Magic] MobArena not found
[13:34:13] [Server thread/INFO]: [Magic] LibsDisguises not found, magic mob disguises will not be available
[13:34:13] [Server thread/INFO]: Resource pack configured in server.properties, Magic not using RP from config.yml
[13:34:13] [Server thread/INFO]: [VehicleStorage] Enabling VehicleStorage v1.1.0
[13:34:13] [Server thread/INFO]: Preparing level "world"
[13:34:14] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[13:34:16] [Worker-Main-3/INFO]: Preparing spawn area: 0%
[13:34:16] [Worker-Main-7/INFO]: Preparing spawn area: 0%
[13:34:16] [Worker-Main-2/INFO]: Preparing spawn area: 0%
[13:34:16] [Worker-Main-6/INFO]: Preparing spawn area: 0%
[13:34:16] [Server thread/INFO]: Time elapsed: 2001 ms
[13:34:16] [Server thread/INFO]: Preparing start region for dimension minecraft:the_nether
[13:34:17] [Worker-Main-3/INFO]: Preparing spawn area: 0%
[13:34:17] [Worker-Main-8/INFO]: Preparing spawn area: 0%
[13:34:17] [Worker-Main-2/INFO]: Preparing spawn area: 0%
[13:34:17] [Server thread/INFO]: Time elapsed: 1141 ms
[13:34:17] [Server thread/INFO]: Preparing start region for dimension minecraft:the_end
[13:34:19] [Worker-Main-4/INFO]: Preparing spawn area: 0%
[13:34:19] [Worker-Main-4/INFO]: Preparing spawn area: 0%
[13:34:19] [Worker-Main-4/INFO]: Preparing spawn area: 0%
[13:34:19] [Worker-Main-4/INFO]: Preparing spawn area: 0%
[13:34:19] [Worker-Main-2/INFO]: Preparing spawn area: 0%
[13:34:19] [Server thread/INFO]: Time elapsed: 2164 ms
[13:34:19] [Server thread/INFO]: [PlayerHeads] Enabling PlayerHeads v5.2.12-SNAPSHOT
[13:34:19] [Server thread/INFO]: [PlayerHeads] NoCheatPlus not detected.
[13:34:19] [Server thread/INFO]: [PlayerHeads] Current plugin compatibility version: craftbukkit 1.16
[13:34:19] [Server thread/INFO]: [dynmap] Enabling dynmap v3.2-beta-2-483
[13:34:20] [Server thread/INFO]: [dynmap] Added 258 custom biome mappings
[13:34:20] [Server thread/INFO]: [dynmap] Using Bukkit Permissions (superperms) for access control
[13:34:20] [Server thread/INFO]: [dynmap] Web interface permissions only available for online users
[13:34:20] [Server thread/INFO]: [dynmap] Mod Support processing completed
[13:34:21] [Server thread/INFO]: [dynmap] Loaded 25 shaders.
[13:34:21] [Server thread/INFO]: [dynmap] Loaded 82 perspectives.
[13:34:21] [Server thread/INFO]: [dynmap] Loaded 22 lightings.
[13:34:21] [Server thread/INFO]: [dynmap] Starting enter/exit processing
[13:34:21] [Dynmap Render Thread/INFO]: [dynmap] Finish marker initialization
[13:34:21] [Server thread/INFO]: [dynmap] Web server started on address 0.0.0.0:8123
[13:34:21] [Server thread/INFO]: [dynmap] version 3.2-beta-2-483 is enabled - core version 3.2-beta-2-483
[13:34:21] [Server thread/INFO]: [dynmap] For support, visit https://reddit.com/r/Dynmap or our Discord at https://discord.gg/s3rd5qn
[13:34:21] [Server thread/INFO]: [dynmap] To report or track bugs, visit https://github.com/webbukkit/dynmap/issues
[13:34:21] [Server thread/INFO]: [dynmap] If you'd like to donate, please visit https://www.patreon.com/dynmap or https://ko-fi.com/michaelprimm
[13:34:21] [Server thread/INFO]: [dynmap] Loaded 3 maps of world 'world'.
[13:34:21] [Server thread/INFO]: [dynmap] Loaded 3129 pending tile renders for world 'world'
[13:34:21] [Server thread/INFO]: [dynmap] Loaded 2 maps of world 'world_nether'.
[13:34:21] [Server thread/INFO]: [dynmap] Loaded 2 maps of world 'world_the_end'.
[13:34:21] [Server thread/INFO]: [dynmap] Enabled
[13:34:21] [Server thread/INFO]: [Enchantments_plus] Enabling Enchantments_plus v4.0.1
[13:34:21] [Server thread/INFO]: [Enchantments_plus] Loading magic compatibillity file, if this step fails you should notify the devs about this.
[13:34:22] [Server thread/INFO]: [Enchantments_plus] Enchantments+ v4.0.1 started up in 261ms
[13:34:22] [Server thread/INFO]: [SMPtweaks] Enabling SMPtweaks v1.0.9-beta
[13:34:22] [Server thread/INFO]: [SMPtweaks] Paper events will be used in order to improve performance
[13:34:22] [Server thread/INFO]: [com.zaxxer.hikari.HikariDataSource] HikariPool-1 - Starting...
[13:34:22] [Server thread/INFO]: [com.zaxxer.hikari.HikariDataSource] HikariPool-1 - Start completed.
[13:34:22] [Server thread/INFO]: [SMPtweaks] Up and running! Startup took 235ms
[13:34:22] [Server thread/INFO]: [ServerMinimap] Enabling ServerMinimap v0.7.24
[13:34:22] [Server thread/INFO]: [ServerMinimap] Created Minimap with ID 0. Use /give <name> MAP 1 0 to get the map as item. (Vanilla command)
[13:34:22] [Server thread/INFO]: [ServerMinimap] Alternative command: /minimap (Plugin command)
[13:34:22] [Server thread/INFO]: [WorldResourcepacks] Enabling WorldResourcepacks v1.8.5 (build 417)
[13:34:22] [Server thread/WARN]: [WorldResourcepacks] You seem to have defined a resource-pack in your server.properties file, if you experience issues then please remove it and configure the pack via this plugin's config directly as it works better when it can completely handle the whole sending itself.
[13:34:22] [Server thread/INFO]: [WorldResourcepacks] Loading config!
[13:34:22] [Server thread/INFO]: [WorldResourcepacks] Debug level: INFO
[13:34:22] [Server thread/INFO]: [WorldResourcepacks] Found locale en
[13:34:22] [Server thread/INFO]: [WorldResourcepacks] [DEBUG] Loading packs:
[13:34:22] [Server thread/INFO]: [WorldResourcepacks] lobbypack - http://example.com/lobbyresourcepack.zip - abcdef012345678abcdef012345678abcdef0123
[13:34:22] [Server thread/INFO]: [WorldResourcepacks] [DEBUG] {url=http://example.com/lobbyresourcepack.zip, hash=abcdef012345678abcdef012345678abcdef0123, format=1, version=1.8, restricted=false, permission=worldresourcepacks.pack.lobbypack, type=null, variants=null}
[13:34:22] [Server thread/INFO]: [WorldResourcepacks] gamepack - 2 variants
[13:34:22] [Server thread/INFO]: [WorldResourcepacks] [DEBUG] {url=null, hash=null, format=null, version=null, restricted=false, permission=worldresourcepacks.pack.gamepack, type=null, variants=[{url=http://example.com/minigameresourcepack_1_15.zip, hash=012345678abcdef012345678abcdef012345678a, format=null, version=1.15, restricted=false, permission=worldresourcepacks.pack.gamepack-variant-1, type=null, variants=null}, {url=http://example.com/minigameresourcepack_1_12.zip, hash=012345678abcdef01234567dddcdef012345678a, format=null, version=1.12, restricted=false, permission=worldresourcepacks.pack.gamepack-variant-2, type=null, variants=null}]}
[13:34:22] [Server thread/INFO]: [WorldResourcepacks] tweaks - https://download.mc-packs.net/pack/4e24a410c924ac94ec2b71dca77c590c3e35d2e3.zip - 4e24a410c924ac94ec2b71dca77c590c3e35d2e3
[13:34:22] [Server thread/INFO]: [WorldResourcepacks] [DEBUG] {url=https://download.mc-packs.net/pack/4e24a410c924ac94ec2b71dca77c590c3e35d2e3.zip, hash=4e24a410c924ac94ec2b71dca77c590c3e35d2e3, format=null, version=null, restricted=false, permission=resourcepacksplugin.pack.tweaks, type=null, variants=null}
[13:34:22] [Server thread/INFO]: [WorldResourcepacks] animation - https://download.mc-packs.net/pack/6425cb0bb71baf3540f64d13eebf9da1730e80ff.zip - 6425cb0bb71baf3540f64d13eebf9da1730e80ff
[13:34:22] [Server thread/INFO]: [WorldResourcepacks] [DEBUG] {url=https://download.mc-packs.net/pack/6425cb0bb71baf3540f64d13eebf9da1730e80ff.zip, hash=6425cb0bb71baf3540f64d13eebf9da1730e80ff, format=null, version=null, restricted=false, permission=resourcepacksplugin.pack.animation, type=null, variants=null}
[13:34:22] [Server thread/INFO]: [WorldResourcepacks] Empty pack - http://cdn.moep.tv/files/Empty.zip - 01517226212d27586ea0c5d6aff1aa5492dd2484
[13:34:22] [Server thread/INFO]: [WorldResourcepacks] Loading global assignment...
[13:34:22] [Server thread/INFO]: [WorldResourcepacks] [DEBUG] Pack: tweaks
[13:34:22] [Server thread/INFO]: [WorldResourcepacks] [DEBUG] Secondary packs:
[13:34:22] [Server thread/INFO]: [WorldResourcepacks] [DEBUG] - animation
[13:34:22] [Server thread/INFO]: [WorldResourcepacks] [DEBUG] Send delay: 10
[13:34:22] [Server thread/INFO]: [WorldResourcepacks] [DEBUG] Loaded PackAssignment{name=global, pack=tweaks, secondaries=[animation], sendDelay=10}
[13:34:22] [Server thread/INFO]: [WorldResourcepacks] Loading world assignments...
[13:34:22] [Server thread/INFO]: [WorldResourcepacks] Loading assignment for world lobby...
[13:34:22] [Server thread/INFO]: [WorldResourcepacks] [DEBUG] Pack: lobbypack
[13:34:22] [Server thread/INFO]: [WorldResourcepacks] [DEBUG] Loaded PackAssignment{name=lobby, pack=lobbypack, secondaries=[], sendDelay=-1}
[13:34:22] [Server thread/INFO]: [WorldResourcepacks] Loading assignment for world minigame...
[13:34:22] [Server thread/INFO]: [WorldResourcepacks] [DEBUG] Regex: minigame_.*
[13:34:22] [Server thread/INFO]: [WorldResourcepacks] [DEBUG] Pack: gamepack
[13:34:22] [Server thread/INFO]: [WorldResourcepacks] [DEBUG] Loaded PackAssignment{name=minigame, pack=gamepack, secondaries=[], sendDelay=-1, regex=minigame_.*}
[13:34:22] [Server thread/INFO]: [WorldResourcepacks] [DEBUG] Stored packs override assignments: false
[13:34:22] [Server thread/WARN]: [WorldResourcepacks] Could not get version of the server! (1.17.1-R0.1-SNAPSHOT/1.17.1)
[13:34:22] [Server thread/WARN]: java.lang.ClassNotFoundException: net.minecraft.server.v1_17_R1.EntityPlayer
[13:34:22] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:146)
[13:34:22] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103)
[13:34:22] [Server thread/WARN]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
[13:34:22] [Server thread/WARN]: 	at java.base/java.lang.Class.forName0(Native Method)
[13:34:22] [Server thread/WARN]: 	at java.base/java.lang.Class.forName(Class.java:375)
[13:34:22] [Server thread/WARN]: 	at WorldResourcepacks (1).jar//de.themoep.resourcepacksplugin.bukkit.internal.InternalHelper_fallback.<init>(InternalHelper_fallback.java:53)
[13:34:22] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[13:34:22] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:78)
[13:34:22] [Server thread/WARN]: 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[13:34:22] [Server thread/WARN]: 	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
[13:34:22] [Server thread/WARN]: 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
[13:34:22] [Server thread/WARN]: 	at WorldResourcepacks (1).jar//de.themoep.resourcepacksplugin.bukkit.WorldResourcepacks.onEnable(WorldResourcepacks.java:170)
[13:34:22] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[13:34:22] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[13:34:22] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500)
[13:34:22] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:529)
[13:34:22] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:443)
[13:34:22] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:639)
[13:34:22] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:306)
[13:34:22] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1126)
[13:34:22] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316)
[13:34:22] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:831)
[13:34:22] [Server thread/INFO]: [DiscordSRV] Enabling DiscordSRV v1.23.0
[13:34:22] [Server thread/INFO]: [Nova] Enabling Nova v0.4
[13:34:22] [Server thread/INFO]: [Nova] [AdvancementAPI] Generating advancements
[13:34:22] [Server thread/WARN]: Couldn't get pack info for: net.minecraft.server.packs.ResourceNotFoundException: 'pack.mcmeta' in ResourcePack '.\world\datapacks\VanillaTweaks_d941067_UNZIP_ME.zip'
[13:34:22] [Server thread/INFO]: Reloading ResourceManager: Default, terralith-v1-3a.zip, new-in-town-by-kanokarob-v2-7-2.zip, bukkit, VanillaTweaks_c234012.zip
[13:34:23] [Server thread/INFO]: Loaded 7 recipes
[13:34:23] [Log4j2-TF-1-AsyncLogger[AsyncContext@659e0bfd]-1/INFO]: [DiscordSRV] [JDA] Login Successful!
[13:34:24] [Log4j2-TF-1-AsyncLogger[AsyncContext@659e0bfd]-1/INFO]: [DiscordSRV] [JDA] Connected to WebSocket
[13:34:24] [Server thread/INFO]: [EnchantableBlocks] Enabling EnchantableBlocks v3.0.0
[13:34:24] [Server thread/INFO]: Running delayed init tasks
[13:34:24] [Server thread/INFO]: [Magic] Vault not found, 'currency' cost types unavailable
[13:34:24] [Server thread/INFO]: [Magic] Registered currencies: item,mana,xp,health,currency,sp,levels,hunger
[13:34:24] [Craft Scheduler Thread - 2/INFO]: [WorldResourcepacks] Generating hashes...
[13:34:24] [Craft Scheduler Thread - 2/INFO]: [WorldResourcepacks] Downloading lobbypack...
[13:34:24] [Log4j2-TF-1-AsyncLogger[AsyncContext@659e0bfd]-1/INFO]: [DiscordSRV] [JDA] Finished Loading!
[13:34:24] [pool-11-thread-1/INFO]: [DiscordSRV] DiscordSRV is up-to-date. (ae26c8fa7a85120ccb1cf9bc46d8de316c1a5db8)
[13:34:24] [Craft Scheduler Thread - 2/ERROR]: [WorldResourcepacks] Could not load lobbypack! http://example.com/lobbyresourcepack.zip
[13:34:24] [Craft Scheduler Thread - 2/INFO]: [WorldResourcepacks] Downloading gamepack-variant-1...
[13:34:24] [DiscordSRV - Initialization/INFO]: [DiscordSRV] Found server G:Redboy's servers(870701332443570186)
[13:34:24] [DiscordSRV - Initialization/INFO]: [DiscordSRV] - TC:general(870701332443570189)
[13:34:24] [DiscordSRV - Initialization/INFO]: [DiscordSRV] - TC:console(870701589537624155)
[13:34:24] [DiscordSRV - Initialization/INFO]: [DiscordSRV] Console forwarding assigned to channel TC:console(870701589537624155)
[13:34:24] [DiscordSRV - Initialization/INFO]: [DiscordSRV] Enabling dynmap hook
[13:34:24] [DiscordSRV - Initialization/INFO]: [DiscordSRV] No chat plugin hooks enabled
[13:34:25] [Craft Scheduler Thread - 0/INFO]: You're running an outdated version of Nova.
[13:34:25] [Craft Scheduler Thread - 0/INFO]: Please download the latest version at https://spigotmc.org/resources/93648.
[13:34:25] [Craft Scheduler Thread - 2/ERROR]: [WorldResourcepacks] Could not load gamepack-variant-1! http://example.com/minigameresourcepack_1_15.zip
[13:34:25] [Craft Scheduler Thread - 2/INFO]: [WorldResourcepacks] Downloading gamepack-variant-2...
[13:34:25] [Craft Scheduler Thread - 2/ERROR]: [WorldResourcepacks] Could not load gamepack-variant-2! http://example.com/minigameresourcepack_1_12.zip
[13:34:25] [Craft Scheduler Thread - 2/INFO]: [WorldResourcepacks] Downloading tweaks...
[13:34:25] [Server thread/INFO]: [Magic] Loaded 541 spells
[13:34:25] [Server thread/INFO]: [Magic] Loaded 12 progression paths
[13:34:25] [Server thread/INFO]: [Magic] Loaded 16 crafting recipes
[13:34:25] [Server thread/INFO]: [Magic] LogBlock not found
[13:34:25] [Server thread/INFO]: [Magic] Factions not found
[13:34:25] [Server thread/INFO]: [Magic] WorldGuard not found, region protection and pvp checks will not be used.
[13:34:25] [Server thread/INFO]: [Magic] Towny not found, region protection and pvp checks will not be used.
[13:34:25] [Server thread/INFO]: [Magic] Lockette nor LockettePro found, will not integrate.
[13:34:25] [Server thread/INFO]: [Magic] GriefPrevention not found, claim protection will not be used.
[13:34:25] [Server thread/INFO]: [Magic] NoCheatPlus not found, will not integrate.
[13:34:25] [Server thread/INFO]: [Magic] dynmap found, integrating.
[13:34:25] [Server thread/INFO]: [Magic] Citizens not found, Magic trait unavailable.
[13:34:25] [Server thread/INFO]: [Magic] LightAPI not found, Light action will not work
[13:34:25] [Server thread/INFO]: [Magic] Loaded 0 arenas
[13:34:25] [Server thread/INFO]: [Magic] Finished loading configuration
[13:34:25] [Server thread/INFO]: Done (17.877s)! For help, type "help"
[13:34:25] [Server thread/INFO]: Timings Reset
[13:34:25] [Server thread/INFO]: [Magic] Loading image map data from imagemaps.yml
[13:34:25] [Server thread/INFO]: [Magic] Loaded 0 image maps
[13:34:25] [Server thread/INFO]: [Magic] Finished loading data.
[13:34:25] [Craft Scheduler Thread - 2/INFO]: [WorldResourcepacks] SHA 1 hash of tweaks: 4e24a410c924ac94ec2b71dca77c590c3e35d2e3
[13:34:25] [Craft Scheduler Thread - 2/INFO]: [WorldResourcepacks] Downloading animation...
[13:34:25] [Craft Scheduler Thread - 2/INFO]: [WorldResourcepacks] SHA 1 hash of animation: 6425cb0bb71baf3540f64d13eebf9da1730e80ff
[13:34:25] [Craft Scheduler Thread - 2/INFO]: [WorldResourcepacks] Downloading empty...
[13:34:25] [Dynmap Render Thread/INFO]: [dynmap] Loading default resource pack
[13:34:25] [Craft Scheduler Thread - 2/INFO]: [WorldResourcepacks] SHA 1 hash of empty: 01517226212d27586ea0c5d6aff1aa5492dd2484
[13:34:25] [Craft Scheduler Thread - 2/INFO]: [WorldResourcepacks] No hash changed!
[13:34:32] [User Authenticator #1/INFO]: UUID of player MyNameIsRedboy is 3a7d9cb1-89af-4407-9207-01766546d058
[13:34:33] [Server thread/INFO]: MyNameIsRedboy joined the game
[13:34:33] [Server thread/INFO]: MyNameIsRedboy[/127.0.0.1:59504] logged in with entity id 76 at ([world]-2759.92947719741, 100.0536935618521, 17046.518772946263)
[13:34:33] [Server thread/INFO]: [WorldResourcepacks] [DEBUG] MyNameIsRedboy matched assignment global due to main pack
[13:34:33] [Server thread/INFO]: [WorldResourcepacks] [DEBUG] Send pack tweaks (https://download.mc-packs.net/pack/4e24a410c924ac94ec2b71dca77c590c3e35d2e3.zip) to MyNameIsRedboy
[13:34:37] [Server thread/INFO]: MyNameIsRedboy lost connection: Please accept the custom resource pack
[13:34:37] [Server thread/INFO]: MyNameIsRedboy left the game
[13:35:39] [User Authenticator #2/INFO]: UUID of player MyNameIsRedboy is 3a7d9cb1-89af-4407-9207-01766546d058
[13:35:39] [Server thread/INFO]: MyNameIsRedboy joined the game
[13:35:39] [Server thread/INFO]: MyNameIsRedboy[/127.0.0.1:58340] logged in with entity id 334 at ([world]-2759.92947719741, 100.0536935618521, 17046.518772946263)
[13:35:40] [Server thread/INFO]: [WorldResourcepacks] [DEBUG] MyNameIsRedboy matched assignment global due to main pack
[13:35:40] [Server thread/INFO]: [WorldResourcepacks] [DEBUG] Send pack tweaks (https://download.mc-packs.net/pack/4e24a410c924ac94ec2b71dca77c590c3e35d2e3.zip) to MyNameIsRedboy
[13:35:41] [Server thread/WARN]: UUID of added entity already exists: EntityPig['Pig'/579, uuid='0c1fa99a-19af-4aa6-9ab0-4c8ad40e674c', l='ServerLevel[world]', x=-2819.17, y=65.00, z=17184.02, cpos=[-177, 1074], tl=487, v=false, rR=null]
[13:35:55] [Server thread/INFO]: MyNameIsRedboy lost connection: Disconnected
[13:35:55] [Server thread/INFO]: MyNameIsRedboy left the game
[13:37:03] [User Authenticator #3/INFO]: UUID of player MyNameIsRedboy is 3a7d9cb1-89af-4407-9207-01766546d058
[13:37:03] [Server thread/INFO]: MyNameIsRedboy joined the game
[13:37:03] [Server thread/INFO]: MyNameIsRedboy[/127.0.0.1:62477] logged in with entity id 667 at ([world]-2765.392209110397, 65.0, 17054.869244257203)
[13:37:04] [Server thread/INFO]: [WorldResourcepacks] [DEBUG] MyNameIsRedboy matched assignment global due to main pack
[13:37:04] [Server thread/INFO]: [WorldResourcepacks] [DEBUG] Send pack tweaks (https://download.mc-packs.net/pack/4e24a410c924ac94ec2b71dca77c590c3e35d2e3.zip) to MyNameIsRedboy
[13:37:08] [Server thread/INFO]: Disconnecting TextComponent{text='MyNameIsRedboy', siblings=[], style=Style{ color=null, bold=null, italic=null, underlined=null, strikethrough=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null, font=minecraft:default}} due to resource pack rejection
[13:37:08] [Server thread/INFO]: MyNameIsRedboy lost connection: Server requires a custom resource pack
[13:37:08] [Server thread/INFO]: MyNameIsRedboy left the game
[13:37:09] [User Authenticator #3/INFO]: UUID of player MyNameIsRedboy is 3a7d9cb1-89af-4407-9207-01766546d058
[13:37:10] [Server thread/INFO]: MyNameIsRedboy joined the game
[13:37:10] [Server thread/INFO]: MyNameIsRedboy[/127.0.0.1:62483] logged in with entity id 935 at ([world]-2765.392209110397, 65.0, 17054.869244257203)
[13:37:10] [Server thread/INFO]: [WorldResourcepacks] [DEBUG] MyNameIsRedboy matched assignment global due to main pack
[13:37:10] [Server thread/INFO]: [WorldResourcepacks] [DEBUG] Send pack tweaks (https://download.mc-packs.net/pack/4e24a410c924ac94ec2b71dca77c590c3e35d2e3.zip) to MyNameIsRedboy

```

#### What other programs/plugins are you running?

(Plugins most likely not the cause)
DiscordSrv
Dynamap
Enchantableblocks
EnchantmentsPlus
Magic
Nova
Playerheads
ServerMinimap
SmpTweaks
VehicleStorage
WorldResourcepacks

#### What is happening?

When joining the game only one resource pack gets loaded

#### What did you expect to happen?

Both resource packs to get loaded when accepting  server resource pack

**Comment by Phoenix616** [comment]
The Vanilla client can only have one server resourcepack applied at once. There is nothing one can do there besides merging both packs into one zip.
