### ISSUE TITLE
Velocity Console error on startup

### ISSUE THREAD

**Issue by BartosB13** [Phoenix616/ResourcepacksPlugins#77]
The first launch of the plugin. The language file is completely empty. It may be a plugin bug.
Plugin and Velcity latest

```
[22:24:53 INFO] [velocityresourcepacks]: Loading config!
[22:24:53 INFO] [velocityresourcepacks]: Loaded config.yml
[22:24:53 INFO] [velocityresourcepacks]: Loaded players.conf
[22:24:53 INFO] [velocityresourcepacks]: Debug level: INFO
[22:24:53 ERROR] [velocityresourcepacks]: Could not save lang.en.yml to plugins/velocityresourcepacks/languages/lang.en.yml
java.io.IOException: Stream closed
        at java.util.zip.InflaterInputStream.ensureOpen(InflaterInputStream.java:67) ~[?:?]
        at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:142) ~[?:?]
        at java.io.FilterInputStream.read(FilterInputStream.java:132) ~[?:?]
        at java.io.InputStream.transferTo(InputStream.java:782) ~[?:?]
        at java.nio.file.Files.copy(Files.java:3171) ~[?:?]
        at de.themoep.resourcepacksplugin.velocity.libs.lang.velocity.VelocityLanguageConfig.saveConfigResource(VelocityLanguageConfig.java:85) ~[?:?]
        at de.themoep.resourcepacksplugin.velocity.libs.lang.velocity.VelocityLanguageConfig.<init>(VelocityLanguageConfig.java:52) ~[?:?]
        at de.themoep.resourcepacksplugin.velocity.libs.lang.velocity.LanguageManager.lambda$loadConfigs$1(LanguageManager.java:61) ~[?:?]
        at de.themoep.resourcepacksplugin.velocity.libs.lang.LanguageManagerCore$1.visitFile(LanguageManagerCore.java:133) ~[?:?]
        at de.themoep.resourcepacksplugin.velocity.libs.lang.LanguageManagerCore$1.visitFile(LanguageManagerCore.java:127) ~[?:?]
        at java.nio.file.Files.walkFileTree(Files.java:2811) ~[?:?]
        at de.themoep.resourcepacksplugin.velocity.libs.lang.LanguageManagerCore.loadInTree(LanguageManagerCore.java:127) ~[?:?]
        at de.themoep.resourcepacksplugin.velocity.libs.lang.LanguageManagerCore.loadConfigs(LanguageManagerCore.java:95) ~[?:?]
        at de.themoep.resourcepacksplugin.velocity.libs.lang.velocity.LanguageManager.loadConfigs(LanguageManager.java:60) ~[?:?]
        at de.themoep.resourcepacksplugin.velocity.libs.lang.velocity.LanguageManager.<init>(LanguageManager.java:55) ~[?:?]
        at de.themoep.resourcepacksplugin.velocity.libs.lang.velocity.LanguageManager.<init>(LanguageManager.java:44) ~[?:?]
        at de.themoep.resourcepacksplugin.velocity.libs.lang.velocity.LanguageManager.<init>(LanguageManager.java:40) ~[?:?]
        at de.themoep.resourcepacksplugin.velocity.libs.lang.velocity.LanguageManager.<init>(LanguageManager.java:32) ~[?:?]
        at de.themoep.resourcepacksplugin.velocity.VelocityResourcepacks.loadConfig(VelocityResourcepacks.java:243) ~[?:?]
        at de.themoep.resourcepacksplugin.velocity.VelocityResourcepacks.onProxyInitialization(VelocityResourcepacks.java:141) ~[?:?]
        at de.themoep.resourcepacksplugin.velocity.Lmbda$31.execute(Unknown Source) ~[?:?]
        at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56) ~[velocity.jar:3.2.0-SNAPSHOT (git-cc74cf85-b238)]
        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:598) ~[velocity.jar:3.2.0-SNAPSHOT (git-cc74cf85-b238)]
        at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:479) ~[velocity.jar:3.2.0-SNAPSHOT (git-cc74cf85-b238)]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[22:24:53 INFO] [velocityresourcepacks]: Found locale en
```

**Comment by Phoenix616** [comment]
That's odd, maybe Velocity changed something regarding how it handles plugin jar files :S

Which Velocity and plugin version are you using exactly or with which version did that start to happen if you know?
