### ISSUE TITLE
LibreLogin Error

### ISSUE THREAD

**Issue by Funasitien** [Phoenix616/ResourcepacksPlugins#80]
#### Config
<details>
          <summary>Config</summary>

 ```yaml
debug: false
default-language: fr
disable-metrics: true
autogeneratehashes: true
append-hash-to-url: true
usepack-is-temporary: true
stored-packs-override-assignments: false
permanent-pack-remove-time: 30
use-auth-plugin: false
empty:
  url: http://cdn.moep.tv/files/Empty.zip
  hash: 01517226212d27586ea0c5d6aff1aa5492dd2484
global:
  pack: globalpack
  send-delay: 20
servers:
  lobby:
    pack: globalpack
  minigame:
    pack: globalpack
packs:
  globalpack:
    url: http://resourcepack.host/dl/SWjfWdxugVZkHCkdlSININYV0tfuNogz/assets.zip
    hash: f505e05a5a7d8a4c32a460569b9f3a303e61f93a
    restricted: false
    permission: bungeeresourcepacks.pack.globalpack

 ```
 
</details>
 
#### Environment description

Bungeecord 1.20
 
 
#### Full Log
<details>
          <summary>Log</summary>

```log
Exception encountered when loading plugin: BungeeResourcepacks
java.lang.NoSuchMethodError: 'void xyz.kyngs.librelogin.api.event.EventProvider.subscribe(xyz.kyngs.librelogin.api.event.EventType, java.util.function.Consumer)'
        at de.themoep.resourcepacksplugin.bungee.listeners.LibreLoginListener.<init>(LibreLoginListener.java:33) ~[?:?]
        at de.themoep.resourcepacksplugin.bungee.BungeeResourcepacks.onEnable(BungeeResourcepacks.java:234) ~[?:?]
        at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:316) ~[server.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:ec41547:536]
        at net.md_5.bungee.BungeeCord.start(BungeeCord.java:299) ~[server.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:ec41547:536]
        at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:67) ~[server.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:ec41547:536]
        at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15) ~[server.jar:git:Waterfall-Bootstrap:1.20-R0.1-SNAPSHOT:ec41547:536]
```

</details>

#### What other programs/plugins are you running?

LibreLogin

#### What is happening?

Plugin dont load with Libre login

#### What did you expect to happen?

Plugin load. I use the latest dev build

**Comment by Phoenix616** [comment]
Which LibreLogin version are you using?
